### ISSUE TITLE
centos host image site is not available 

### ISSUE THREAD

**Issue by ismayilkm** [craig5/salt-essentials-utils#2]
we are not able to get chef/centos 6.6 hots site

**Comment by jeton** [comment]
I think they have been moved to: https://atlas.hashicorp.com/bento/

**Comment by pabranch** [comment]
Fixed by PR #4

**Comment by craig5** [comment]
I merged PR #5 which should fix your issue.

Sorry for the massive delay.

**Comment by ismayilkm** [comment]
Thank you so much
